/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package axfr;

import org.xbill.DNS.Name;
import org.xbill.DNS.TSIG;
import org.xbill.DNS.Zone;
import org.xbill.DNS.ZoneTransferIn;

public class App {
    public static void main(String[] args) throws Exception {
//        Name name = new Name( "9.in-addr.arpa." );  // small zone (1 message)
//        Name name = new Name( "135.in-addr.arpa." ); // medium zone (2 messages)
        Name name = new Name( "192.in-addr.arpa." ); // large zone (many messages)

        TSIG tsig = new TSIG("HmacSHA256", "your_name_here", "your_key_here");
        ZoneTransferIn client = ZoneTransferIn.newAXFR( name, "ns0.example.com", 53, tsig );

        var handler = new ZoneBuilderAxfrHandler( name );
        client.run( handler );

        Zone z = handler.getZone();
        System.out.print( z.toMasterFile() );
    }
}
